services:
  - docker:18.09-dind
    alias:dockerhost

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://dockerhost:2375

stages:
  - check
  - build

check:
  image: golangci/golangci-lint:v1.27
  stage: check
  script:
    - make check

build:
  image: golang:1.14
  stage: build
  script:
    - make build
