variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09-dind

stages:
  - check
  - build

check:
  image: golangci/golangci-lint
  stage: check
  script:
    - make check

build:
  image: golang:1.17
  stage: build
  script:
    - make build
